account_id = "e187dafb9c5a119daf5c9e5496b8aff2"

name = "square-cell-10b1"
main = "index.js"
compatibility_date = "2023-02-03"

workers_dev = false
route = { pattern = "quickna.me", custom_domain = true }

kv_namespaces = [
  { binding = "KV_STORE", id = "e31284fa2fd64cf18808e1b3180d0e86" }
]
