account_id = "e187dafb9c5a119daf5c9e5496b8aff2"
name = "square-cell-10b1"
type = "javascript"

workers_dev = true

routes = [
  { pattern = "quickna.me", custom_domain = true }
]
zone_id = "cbac25da80f1dc9d98759d1228bbfa20"

kv_namespaces = [
  { binding = "KV_STORE", id = "e31284fa2fd64cf18808e1b3180d0e86" }
]
