name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify (Stage 1)
        uses: nizarmah/auto-minify@v2.1
        with:
          maxdepth: 1

      - name: Minify (Stage 2)
        run: |
          # Replace the original file with the minified file.
          mv "index.min.js" "index.js"

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
              TOTP_SECRET
        env:
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
